#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"
#include "/Engine/Private/ScreenPass.ush"

Texture2D SceneDepthTexture;
SamplerState SceneDepthSampler;

void CaptureDepthPS(
    in noperspective float4 UVAndScreenPos : TEXCOORD0,
    out float OutDepth : SV_Target0
)
{
    float2 UV = UVAndScreenPos.xy;
    float DeviceZ = Texture2DSample(SceneDepthTexture, SceneDepthSampler, UV).r;
    OutDepth = ConvertFromDeviceZ(DeviceZ);
}
