# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import VCCSim_pb2 as VCCSim__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in VCCSim_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecordingServiceStub(object):
    """Services:
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recording = channel.unary_unary(
                '/VCCSim.RecordingService/Recording',
                request_serializer=VCCSim__pb2.EmptyRequest.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)


class RecordingServiceServicer(object):
    """Services:
    """

    def Recording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecordingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recording': grpc.unary_unary_rpc_method_handler(
                    servicer.Recording,
                    request_deserializer=VCCSim__pb2.EmptyRequest.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VCCSim.RecordingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VCCSim.RecordingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecordingService(object):
    """Services:
    """

    @staticmethod
    def Recording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.RecordingService/Recording',
            VCCSim__pb2.EmptyRequest.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LidarServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLiDARData = channel.unary_unary(
                '/VCCSim.LidarService/GetLiDARData',
                request_serializer=VCCSim__pb2.RobotName.SerializeToString,
                response_deserializer=VCCSim__pb2.LidarData.FromString,
                _registered_method=True)
        self.GetLiDAROdom = channel.unary_unary(
                '/VCCSim.LidarService/GetLiDAROdom',
                request_serializer=VCCSim__pb2.RobotName.SerializeToString,
                response_deserializer=VCCSim__pb2.Odometry.FromString,
                _registered_method=True)
        self.GetLiDARDataAndOdom = channel.unary_unary(
                '/VCCSim.LidarService/GetLiDARDataAndOdom',
                request_serializer=VCCSim__pb2.RobotName.SerializeToString,
                response_deserializer=VCCSim__pb2.LidarDataAndOdom.FromString,
                _registered_method=True)


class LidarServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLiDARData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLiDAROdom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLiDARDataAndOdom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LidarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLiDARData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLiDARData,
                    request_deserializer=VCCSim__pb2.RobotName.FromString,
                    response_serializer=VCCSim__pb2.LidarData.SerializeToString,
            ),
            'GetLiDAROdom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLiDAROdom,
                    request_deserializer=VCCSim__pb2.RobotName.FromString,
                    response_serializer=VCCSim__pb2.Odometry.SerializeToString,
            ),
            'GetLiDARDataAndOdom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLiDARDataAndOdom,
                    request_deserializer=VCCSim__pb2.RobotName.FromString,
                    response_serializer=VCCSim__pb2.LidarDataAndOdom.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VCCSim.LidarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VCCSim.LidarService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LidarService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLiDARData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.LidarService/GetLiDARData',
            VCCSim__pb2.RobotName.SerializeToString,
            VCCSim__pb2.LidarData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLiDAROdom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.LidarService/GetLiDAROdom',
            VCCSim__pb2.RobotName.SerializeToString,
            VCCSim__pb2.Odometry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLiDARDataAndOdom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.LidarService/GetLiDARDataAndOdom',
            VCCSim__pb2.RobotName.SerializeToString,
            VCCSim__pb2.LidarDataAndOdom.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CameraServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRGBData = channel.unary_unary(
                '/VCCSim.CameraService/GetRGBData',
                request_serializer=VCCSim__pb2.IndexedCamera.SerializeToString,
                response_deserializer=VCCSim__pb2.RGBData.FromString,
                _registered_method=True)
        self.GetDepthData = channel.unary_unary(
                '/VCCSim.CameraService/GetDepthData',
                request_serializer=VCCSim__pb2.IndexedCamera.SerializeToString,
                response_deserializer=VCCSim__pb2.DepthData.FromString,
                _registered_method=True)
        self.GetDepthPointCloud = channel.unary_unary(
                '/VCCSim.CameraService/GetDepthPointCloud',
                request_serializer=VCCSim__pb2.IndexedCamera.SerializeToString,
                response_deserializer=VCCSim__pb2.TPointCloud.FromString,
                _registered_method=True)
        self.GetSegData = channel.unary_unary(
                '/VCCSim.CameraService/GetSegData',
                request_serializer=VCCSim__pb2.IndexedCamera.SerializeToString,
                response_deserializer=VCCSim__pb2.RGBData.FromString,
                _registered_method=True)
        self.GetNormalData = channel.unary_unary(
                '/VCCSim.CameraService/GetNormalData',
                request_serializer=VCCSim__pb2.IndexedCamera.SerializeToString,
                response_deserializer=VCCSim__pb2.NormalData.FromString,
                _registered_method=True)


class CameraServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRGBData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDepthData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDepthPointCloud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSegData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNormalData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRGBData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRGBData,
                    request_deserializer=VCCSim__pb2.IndexedCamera.FromString,
                    response_serializer=VCCSim__pb2.RGBData.SerializeToString,
            ),
            'GetDepthData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDepthData,
                    request_deserializer=VCCSim__pb2.IndexedCamera.FromString,
                    response_serializer=VCCSim__pb2.DepthData.SerializeToString,
            ),
            'GetDepthPointCloud': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDepthPointCloud,
                    request_deserializer=VCCSim__pb2.IndexedCamera.FromString,
                    response_serializer=VCCSim__pb2.TPointCloud.SerializeToString,
            ),
            'GetSegData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSegData,
                    request_deserializer=VCCSim__pb2.IndexedCamera.FromString,
                    response_serializer=VCCSim__pb2.RGBData.SerializeToString,
            ),
            'GetNormalData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNormalData,
                    request_deserializer=VCCSim__pb2.IndexedCamera.FromString,
                    response_serializer=VCCSim__pb2.NormalData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VCCSim.CameraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VCCSim.CameraService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CameraService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRGBData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.CameraService/GetRGBData',
            VCCSim__pb2.IndexedCamera.SerializeToString,
            VCCSim__pb2.RGBData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDepthData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.CameraService/GetDepthData',
            VCCSim__pb2.IndexedCamera.SerializeToString,
            VCCSim__pb2.DepthData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDepthPointCloud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.CameraService/GetDepthPointCloud',
            VCCSim__pb2.IndexedCamera.SerializeToString,
            VCCSim__pb2.TPointCloud.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSegData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.CameraService/GetSegData',
            VCCSim__pb2.IndexedCamera.SerializeToString,
            VCCSim__pb2.RGBData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNormalData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.CameraService/GetNormalData',
            VCCSim__pb2.IndexedCamera.SerializeToString,
            VCCSim__pb2.NormalData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DroneServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDronePose = channel.unary_unary(
                '/VCCSim.DroneService/GetDronePose',
                request_serializer=VCCSim__pb2.RobotName.SerializeToString,
                response_deserializer=VCCSim__pb2.Pose.FromString,
                _registered_method=True)
        self.SendDronePose = channel.unary_unary(
                '/VCCSim.DroneService/SendDronePose',
                request_serializer=VCCSim__pb2.DronePose.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)
        self.SendDronePath = channel.unary_unary(
                '/VCCSim.DroneService/SendDronePath',
                request_serializer=VCCSim__pb2.DronePath.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)
        self.MoveToNext = channel.unary_unary(
                '/VCCSim.DroneService/MoveToNext',
                request_serializer=VCCSim__pb2.RobotName.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)


class DroneServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDronePose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendDronePose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendDronePath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveToNext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DroneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDronePose': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDronePose,
                    request_deserializer=VCCSim__pb2.RobotName.FromString,
                    response_serializer=VCCSim__pb2.Pose.SerializeToString,
            ),
            'SendDronePose': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDronePose,
                    request_deserializer=VCCSim__pb2.DronePose.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
            'SendDronePath': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDronePath,
                    request_deserializer=VCCSim__pb2.DronePath.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
            'MoveToNext': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveToNext,
                    request_deserializer=VCCSim__pb2.RobotName.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VCCSim.DroneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VCCSim.DroneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DroneService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDronePose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.DroneService/GetDronePose',
            VCCSim__pb2.RobotName.SerializeToString,
            VCCSim__pb2.Pose.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendDronePose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.DroneService/SendDronePose',
            VCCSim__pb2.DronePose.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendDronePath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.DroneService/SendDronePath',
            VCCSim__pb2.DronePath.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveToNext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.DroneService/MoveToNext',
            VCCSim__pb2.RobotName.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FlashServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFlashPose = channel.unary_unary(
                '/VCCSim.FlashService/GetFlashPose',
                request_serializer=VCCSim__pb2.RobotName.SerializeToString,
                response_deserializer=VCCSim__pb2.Pose.FromString,
                _registered_method=True)
        self.SendFlashPose = channel.unary_unary(
                '/VCCSim.FlashService/SendFlashPose',
                request_serializer=VCCSim__pb2.DronePose.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)
        self.SendFlashPath = channel.unary_unary(
                '/VCCSim.FlashService/SendFlashPath',
                request_serializer=VCCSim__pb2.DronePath.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)
        self.CheckReady = channel.unary_unary(
                '/VCCSim.FlashService/CheckReady',
                request_serializer=VCCSim__pb2.RobotName.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)
        self.MoveToNext = channel.unary_unary(
                '/VCCSim.FlashService/MoveToNext',
                request_serializer=VCCSim__pb2.RobotName.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)


class FlashServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFlashPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFlashPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFlashPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveToNext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlashServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFlashPose': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlashPose,
                    request_deserializer=VCCSim__pb2.RobotName.FromString,
                    response_serializer=VCCSim__pb2.Pose.SerializeToString,
            ),
            'SendFlashPose': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFlashPose,
                    request_deserializer=VCCSim__pb2.DronePose.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
            'SendFlashPath': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFlashPath,
                    request_deserializer=VCCSim__pb2.DronePath.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
            'CheckReady': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckReady,
                    request_deserializer=VCCSim__pb2.RobotName.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
            'MoveToNext': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveToNext,
                    request_deserializer=VCCSim__pb2.RobotName.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VCCSim.FlashService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VCCSim.FlashService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlashService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFlashPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.FlashService/GetFlashPose',
            VCCSim__pb2.RobotName.SerializeToString,
            VCCSim__pb2.Pose.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendFlashPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.FlashService/SendFlashPose',
            VCCSim__pb2.DronePose.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendFlashPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.FlashService/SendFlashPath',
            VCCSim__pb2.DronePath.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.FlashService/CheckReady',
            VCCSim__pb2.RobotName.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveToNext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.FlashService/MoveToNext',
            VCCSim__pb2.RobotName.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CarServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCarOdom = channel.unary_unary(
                '/VCCSim.CarService/GetCarOdom',
                request_serializer=VCCSim__pb2.RobotName.SerializeToString,
                response_deserializer=VCCSim__pb2.Odometry.FromString,
                _registered_method=True)
        self.SendCarPose = channel.unary_unary(
                '/VCCSim.CarService/SendCarPose',
                request_serializer=VCCSim__pb2.CarPose.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)
        self.SendCarPath = channel.unary_unary(
                '/VCCSim.CarService/SendCarPath',
                request_serializer=VCCSim__pb2.CarPath.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)
        self.MoveToNext = channel.unary_unary(
                '/VCCSim.CarService/MoveToNext',
                request_serializer=VCCSim__pb2.RobotName.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)


class CarServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCarOdom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCarPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCarPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveToNext(self, request, context):
        """todo: implement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCarOdom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCarOdom,
                    request_deserializer=VCCSim__pb2.RobotName.FromString,
                    response_serializer=VCCSim__pb2.Odometry.SerializeToString,
            ),
            'SendCarPose': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCarPose,
                    request_deserializer=VCCSim__pb2.CarPose.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
            'SendCarPath': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCarPath,
                    request_deserializer=VCCSim__pb2.CarPath.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
            'MoveToNext': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveToNext,
                    request_deserializer=VCCSim__pb2.RobotName.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VCCSim.CarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VCCSim.CarService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CarService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCarOdom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.CarService/GetCarOdom',
            VCCSim__pb2.RobotName.SerializeToString,
            VCCSim__pb2.Odometry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCarPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.CarService/SendCarPose',
            VCCSim__pb2.CarPose.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCarPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.CarService/SendCarPath',
            VCCSim__pb2.CarPath.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveToNext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.CarService/MoveToNext',
            VCCSim__pb2.RobotName.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MeshServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMesh = channel.unary_unary(
                '/VCCSim.MeshService/SendMesh',
                request_serializer=VCCSim__pb2.MeshData.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)
        self.SendGlobalMesh = channel.unary_unary(
                '/VCCSim.MeshService/SendGlobalMesh',
                request_serializer=VCCSim__pb2.MeshData.SerializeToString,
                response_deserializer=VCCSim__pb2.MeshID.FromString,
                _registered_method=True)
        self.RemoveGlobalMesh = channel.unary_unary(
                '/VCCSim.MeshService/RemoveGlobalMesh',
                request_serializer=VCCSim__pb2.MeshID.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)


class MeshServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMesh(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendGlobalMesh(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveGlobalMesh(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeshServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMesh': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMesh,
                    request_deserializer=VCCSim__pb2.MeshData.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
            'SendGlobalMesh': grpc.unary_unary_rpc_method_handler(
                    servicer.SendGlobalMesh,
                    request_deserializer=VCCSim__pb2.MeshData.FromString,
                    response_serializer=VCCSim__pb2.MeshID.SerializeToString,
            ),
            'RemoveGlobalMesh': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveGlobalMesh,
                    request_deserializer=VCCSim__pb2.MeshID.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VCCSim.MeshService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VCCSim.MeshService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeshService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMesh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.MeshService/SendMesh',
            VCCSim__pb2.MeshData.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendGlobalMesh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.MeshService/SendGlobalMesh',
            VCCSim__pb2.MeshData.SerializeToString,
            VCCSim__pb2.MeshID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveGlobalMesh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.MeshService/RemoveGlobalMesh',
            VCCSim__pb2.MeshID.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PointCloudServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendPointCloudWithColor = channel.unary_unary(
                '/VCCSim.PointCloudService/SendPointCloudWithColor',
                request_serializer=VCCSim__pb2.ColoredPointCloud.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)


class PointCloudServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendPointCloudWithColor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PointCloudServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendPointCloudWithColor': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPointCloudWithColor,
                    request_deserializer=VCCSim__pb2.ColoredPointCloud.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VCCSim.PointCloudService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VCCSim.PointCloudService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PointCloudService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendPointCloudWithColor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.PointCloudService/SendPointCloudWithColor',
            VCCSim__pb2.ColoredPointCloud.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SafeCheckServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckSafetyPawn = channel.unary_unary(
                '/VCCSim.SafeCheckService/CheckSafetyPawn',
                request_serializer=VCCSim__pb2.RobotName.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)
        self.CheckSafetyPosition = channel.unary_unary(
                '/VCCSim.SafeCheckService/CheckSafetyPosition',
                request_serializer=VCCSim__pb2.Vec3f.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)
        self.CheckSafetyDronePath = channel.unary_unary(
                '/VCCSim.SafeCheckService/CheckSafetyDronePath',
                request_serializer=VCCSim__pb2.DronePath.SerializeToString,
                response_deserializer=VCCSim__pb2.Status.FromString,
                _registered_method=True)


class SafeCheckServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckSafetyPawn(self, request, context):
        """todo: implement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSafetyPosition(self, request, context):
        """todo: implement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSafetyDronePath(self, request, context):
        """todo: implement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SafeCheckServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckSafetyPawn': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSafetyPawn,
                    request_deserializer=VCCSim__pb2.RobotName.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
            'CheckSafetyPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSafetyPosition,
                    request_deserializer=VCCSim__pb2.Vec3f.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
            'CheckSafetyDronePath': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSafetyDronePath,
                    request_deserializer=VCCSim__pb2.DronePath.FromString,
                    response_serializer=VCCSim__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VCCSim.SafeCheckService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VCCSim.SafeCheckService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SafeCheckService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckSafetyPawn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.SafeCheckService/CheckSafetyPawn',
            VCCSim__pb2.RobotName.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckSafetyPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.SafeCheckService/CheckSafetyPosition',
            VCCSim__pb2.Vec3f.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckSafetyDronePath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VCCSim.SafeCheckService/CheckSafetyDronePath',
            VCCSim__pb2.DronePath.SerializeToString,
            VCCSim__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
