/*
* Copyright (C) 2025 Visual Computing Research Center, Shenzhen University
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#include "Utils/ImageProcesser.h"
#include "Sensors/CameraSensor.h"
#include "ImageUtils.h"
#include "IImageWrapper.h"
#include "IImageWrapperModule.h"

DEFINE_LOG_CATEGORY_STATIC(LogImageProcesser, Log, All);

void FAsyncImageSaveTask::DoWork()
{
    TArray64<uint8> CompressedBitmap;
    FImageUtils::PNGCompressImageArray(Size.X, Size.Y, Pixels,
       CompressedBitmap);

    if (!FFileHelper::SaveArrayToFile(CompressedBitmap, *FilePath))
    {
       UE_LOG(LogImageProcesser, Error, TEXT("Failed to save render target to file."));
    }
}

void FAsyncDepthSaveTask::DoWork()
{
    // Convert depth data to 16-bit grayscale
    TArray<uint16> DepthData16;
    DepthData16.Reserve(DepthPixels.Num());

    for (const float& DepthPixel : DepthPixels)
    {
        uint16 Depth16 = FMath::Clamp(
            FMath::RoundToInt(DepthPixel),
            0,
            65535
        );
        DepthData16.Add(Depth16);
    }
    
    // Get image wrapper module
    IImageWrapperModule& ImageWrapperModule =
        FModuleManager::LoadModuleChecked<IImageWrapperModule>(FName("ImageWrapper"));
    TSharedPtr<IImageWrapper> ImageWrapper =
        ImageWrapperModule.CreateImageWrapper(EImageFormat::PNG);
    
    if (ImageWrapper.IsValid())
    {
        // Convert uint16 array to uint8 array for image wrapper (little endian)
        TArray<uint8> RawData;
        RawData.Reserve(DepthData16.Num() * 2);
        
        for (uint16 Value : DepthData16)
        {
            RawData.Add(Value & 0xFF);        // Low byte
            RawData.Add((Value >> 8) & 0xFF); // High byte
        }
        
        if (ImageWrapper->SetRaw(
            RawData.GetData(), 
            RawData.Num(), 
            Size.X, 
            Size.Y, 
            ERGBFormat::Gray, 
            16
        ))
        {
            // Get compressed PNG data
            TArray64<uint8> CompressedData = ImageWrapper->GetCompressed();
            
            // Save to file
            if (!FFileHelper::SaveArrayToFile(CompressedData, *FilePath))
            {
                UE_LOG(LogImageProcesser, Error, TEXT("Failed to save 16-bit depth "
                                            "image to file: %s"), *FilePath);
            }
        }
        else
        {
            UE_LOG(LogImageProcesser, Error, TEXT("Failed to set raw data for 16-bit "
                                        "depth image: %s"), *FilePath);
        }
    }
    else
    {
        UE_LOG(LogImageProcesser, Error, TEXT("Failed to create PNG image wrapper "
                                    "for 16-bit depth saving"));
    }
}

void FAsyncPLYSaveTask::DoWork()
{
    if (PointCloud.Num() == 0)
    {
        UE_LOG(LogImageProcesser, Warning, TEXT("FAsyncPLYSaveTask: "
                                      "No points to save to %s"), *FilePath);
        return;
    }

    // Create PLY file content
    FString PLYContent;
        
    // PLY header
    PLYContent += TEXT("ply\n");
    PLYContent += TEXT("format ascii 1.0\n");
    PLYContent += FString::Printf(TEXT("comment Point Cloud generated by UE - %s\n"), 
        *FDateTime::Now().ToString());
    PLYContent += TEXT("comment UE Coordinate System: X=Forward, Y=Right, Z=Up (left-handed)\n");
    PLYContent += TEXT("comment Units: centimeters\n");
    PLYContent += FString::Printf(TEXT("element vertex %d\n"), PointCloud.Num());
    PLYContent += TEXT("property float x\n");
    PLYContent += TEXT("property float y\n");
    PLYContent += TEXT("property float z\n");
    PLYContent += TEXT("property uchar red\n");
    PLYContent += TEXT("property uchar green\n");
    PLYContent += TEXT("property uchar blue\n");
    PLYContent += TEXT("end_header\n");
        
    // Write vertex data
    for (const FDCPoint& Point : PointCloud)
    {
        const FVector& Loc = Point.Location;
            
        // Add point with default white color (you can modify this for depth-based coloring)
        PLYContent += FString::Printf(TEXT("%.6f %.6f %.6f 255 255 255\n"), 
            Loc.X, Loc.Y, Loc.Z);
    }
        
    // Save to file
    if (!FFileHelper::SaveStringToFile(PLYContent, *FilePath))
    {
        UE_LOG(LogImageProcesser, Error, TEXT("Failed to save PLY point cloud to file: %s"), *FilePath);
    }
    else
    {
        UE_LOG(LogImageProcesser, Log, TEXT("Successfully saved %d points to PLY file: %s"), 
            PointCloud.Num(), *FilePath);
    }
}

void FAsyncNormalEXRSaveTask::DoWork()
{
    // Use modern UE image API with FImage
    FImage Image;
    Image.Init(Size.X, Size.Y, ERawImageFormat::RGBA32F);

    // Convert FLinearColor to FImage data
    TArrayView64<FLinearColor> ImageData = Image.AsRGBA32F();

    if (ImageData.Num() != NormalPixels.Num())
    {
        UE_LOG(LogImageProcesser, Error, TEXT("Image data size mismatch: Expected %lld, got %d"),
            ImageData.Num(), NormalPixels.Num());
        return;
    }

    // Copy normal data to image
    for (int32 i = 0; i < NormalPixels.Num(); ++i)
    {
        ImageData[i] = NormalPixels[i];
    }

    // Get image wrapper module
    IImageWrapperModule& ImageWrapperModule =
        FModuleManager::LoadModuleChecked<IImageWrapperModule>(FName("ImageWrapper"));

    // Compress image using modern API
    TArray64<uint8> CompressedData;
    bool bSuccess = ImageWrapperModule.CompressImage(
        CompressedData,
        EImageFormat::EXR,
        Image,
        100
    );

    if (bSuccess && CompressedData.Num() > 0)
    {
        // Save to file
        if (!FFileHelper::SaveArrayToFile(CompressedData, *FilePath))
        {
            UE_LOG(LogImageProcesser, Error, TEXT("Failed to save EXR normal image to file: %s"), *FilePath);
        }
    }
    else
    {
        UE_LOG(LogImageProcesser, Error, TEXT("Failed to compress normal image to EXR format"));
    }
}

void FAsyncDepthVisualSaveTask::CalculateDynamicRange(float& OutMinRange, float& OutMaxRange) const
{
    if (DepthData.Num() == 0)
    {
        OutMinRange = 0.0f;
        OutMaxRange = 1.0f;
        return;
    }

    // Copy and sort data for percentile calculation
    TArray<float> SortedDepths = DepthData;
    SortedDepths.Sort();

    // Filter out invalid values (negative, infinite, or NaN)
    SortedDepths.RemoveAll([](float Depth) {
        return Depth < 0.0f || !FMath::IsFinite(Depth);
    });

    if (SortedDepths.Num() == 0)
    {
        OutMinRange = 0.0f;
        OutMaxRange = 1.0f;
        return;
    }

    // Use 2nd and 98th percentiles to exclude outliers
    int32 LowIndex = FMath::FloorToInt(SortedDepths.Num() * 0.02f);
    int32 HighIndex = FMath::FloorToInt(SortedDepths.Num() * 0.98f);

    LowIndex = FMath::Clamp(LowIndex, 0, SortedDepths.Num() - 1);
    HighIndex = FMath::Clamp(HighIndex, LowIndex, SortedDepths.Num() - 1);

    OutMinRange = SortedDepths[LowIndex];
    OutMaxRange = SortedDepths[HighIndex];

    // Ensure we have a valid range
    if (OutMaxRange <= OutMinRange)
    {
        OutMaxRange = OutMinRange + 1.0f;
    }

    UE_LOG(LogImageProcesser, Log, TEXT("Dynamic depth range: [%.2f, %.2f] from %d valid samples"),
        OutMinRange, OutMaxRange, SortedDepths.Num());
}

void FAsyncDepthVisualSaveTask::DoWork()
{
    if (DepthData.Num() == 0)
    {
        UE_LOG(LogImageProcesser, Warning, TEXT("No depth data to save"));
        return;
    }

    // Calculate dynamic range based on actual depth distribution
    float DynamicMinRange, DynamicMaxRange;
    CalculateDynamicRange(DynamicMinRange, DynamicMaxRange);

    // Create visual-friendly depth image with dynamic range mapping
    TArray<FColor> VisualPixels;
    VisualPixels.Reserve(DepthData.Num());

    // Apply range clamping and invert for visual appeal (closer = darker, farther = lighter)
    for (float Depth : DepthData)
    {
        // Clamp depth to the dynamically calculated range
        float ClampedDepth = FMath::Clamp(Depth, DynamicMinRange, DynamicMaxRange);

        // Normalize to [0,1] range, then invert (1-x) for visual appeal
        float NormalizedDepth = (ClampedDepth - DynamicMinRange) / (DynamicMaxRange - DynamicMinRange);
        float InvertedDepth = 1.0f - NormalizedDepth;

        // Apply gamma correction for better visual distribution
        float GammaCorrected = FMath::Pow(InvertedDepth, 0.5f);

        // Convert to 8-bit grayscale
        uint8 GrayValue = FMath::RoundToInt(GammaCorrected * 255.0f);
        VisualPixels.Add(FColor(GrayValue, GrayValue, GrayValue, 255));
    }

    // Save using existing PNG compression
    TArray64<uint8> CompressedBitmap;
    FImageUtils::PNGCompressImageArray(Size.X, Size.Y, VisualPixels, CompressedBitmap);

    if (!FFileHelper::SaveArrayToFile(CompressedBitmap, *FilePath))
    {
        UE_LOG(LogImageProcesser, Error, TEXT("Failed to save visual depth image to file: %s"), *FilePath);
    }
}

void FAsyncNormalVisualSaveTask::DoWork()
{
    if (NormalPixels.Num() == 0)
    {
        UE_LOG(LogImageProcesser, Warning, TEXT("No normal data to save"));
        return;
    }

    // Convert normal vectors to visual RGB representation
    TArray<FColor> VisualPixels;
    VisualPixels.Reserve(NormalPixels.Num());

    for (const FLinearColor& Normal : NormalPixels)
    {
        // Convert from [-1,1] normal space to [0,255] RGB space
        // Normal vectors are typically in world space, so we need to handle the mapping carefully
        FVector NormalVec(Normal.R, Normal.G, Normal.B);

        // Normalize the vector to ensure it's a unit vector
        NormalVec.Normalize();

        // Map from [-1,1] to [0,255]
        uint8 R = FMath::RoundToInt((NormalVec.X + 1.0f) * 127.5f);
        uint8 G = FMath::RoundToInt((NormalVec.Y + 1.0f) * 127.5f);
        uint8 B = FMath::RoundToInt((NormalVec.Z + 1.0f) * 127.5f);

        VisualPixels.Add(FColor(R, G, B, 255));
    }

    // Save using existing PNG compression
    TArray64<uint8> CompressedBitmap;
    FImageUtils::PNGCompressImageArray(Size.X, Size.Y, VisualPixels, CompressedBitmap);

    if (!FFileHelper::SaveArrayToFile(CompressedBitmap, *FilePath))
    {
        UE_LOG(LogImageProcesser, Error, TEXT("Failed to save visual normal image to file: %s"), *FilePath);
    }
}