# Attention!
# Length unit is in centimeter.
# Angle unit is in degree.
# Left-handed coordinate system.
# Just as UE5.

[VCCSimPresets]

IP = "0.0.0.0"
Port = 50996

MainCharacter = "Flash"                         # Name or Tag, but tag is recommended.
StaticMeshActor = ["MFMesh", "CompanionCube"]   # Name or Tag

SubWindows = ["Lit", "Unit", "PointCloud"]
SubWindowsOpacities = [0.95, 0.85, 0.75]
StartWithRecording = false
UseMeshManager = true
MeshMaterial = "VCCSim/Materials/MFMeshMaterial.MFMeshMaterial"
LS_StartOffset = 0                              # Frame
BufferSize = 100
LogSavePath = "C:/UEProjects/VCCSimDev/Plugins/VCCSim/Logs"
DefaultDronePawn = "/VCCSim/Pawn/Drone/BP_PreciseDrone_1C_1D_L.BP_PreciseDrone_1C_1D_L_C"
DefaultCarPawn = "/VCCSim/Pawn/Husky/Blueprints/BP_CarPawn_Husky.BP_CarPawn_Husky_C"
DefaultFlashPawn = "/VCCSim/Pawn/Flash/BP_FlashPawn.BP_FlashPawn_C"

#[[Robots]]
#
#UETag = "Mavic"
#Type = "Drone"
#RecordInterval = 0.5
#
#[Robots.ComponentConfigs.Lidar]
#RecordInterval = 0.5
#NumRays = 32
#NumPoints = 16000
#ScannerRangeInner = 300
#ScannerRangeOuter = 3000
#ScannerAngleUp = 25
#ScannerAngleDown = 25
#bVisualizePoints = true
#
#[Robots.ComponentConfigs.RGBCamera]
#RecordInterval = 0.5
#FOV = 90
#Width = 1500
#Height = 800
#bOrthographic = false

#[Robots.ComponentConfigs.DepthCamera]
#FOV = 90
#Width = 512
#Height = 512
#MaxRange = 2000.0
#MinRange = 0.0
#bOrthographic = false

#[[Robots]]
#
#UETag = "Husky"
#Type = "Car"
#
#[Robots.ComponentConfigs.Lidar]
#NumRays = 32
#NumPoints = 16000
#ScannerRangeInner = 100
#ScannerRangeOuter = 4000
#ScannerAngleUp = 35
#ScannerAngleDown = 25
#bVisualizePoints = true

[[Robots]]

UETag = "Flash"
Type = "Flash"
RecordInterval = -1

[Robots.ComponentConfigs.RGBCamera]
RecordInterval = -1
FOV = 90
Width = 800
Height = 600
bOrthographic = false