# Attention!
# Length unit is in centimeter.
# Angle unit is in degree.
# Left-handed coordinate system.
# Just as UE5.

[VCCSimPresets]

IP = "0.0.0.0"
Port = 50996

# Name or Tag, but tag is recommended.
# If there is only one robot, the tag is not necessary.
MainCharacter = "Mavic"
StaticMeshActor = ["MFMesh", "CompanionCube"]   # Name or Tag
ManualControl = false

SubWindows = ["Lit", "Unit", "PointCloud", "RGB", "Depth", "Segmentation", "Normal"]
SubWindowsOpacities = [0.95, 0.85, 0.75, 0.95, 0.95, 0.75, 0.9]

StartWithRecording = true
BetterVisualsRecording = false

UseMeshManager = false
MeshMaterial = "/VCCSim/Materials/M_Static_mesh"

LS_StartOffset = 0                              # Frame

DefaultDronePawn = "/VCCSim/Pawn/Drone/BP_PreciseDrone_1C_1D_L.BP_PreciseDrone_1C_1D_L_C"
DefaultCarPawn = "/VCCSim/Pawn/Husky/Blueprints/BP_CarPawn_Husky.BP_CarPawn_Husky_C"
DefaultFlashPawn = "/VCCSim/Pawn/Flash/BP_FlashPawn.BP_FlashPawn_C"


[[Robots]]
UETag = "Mavic"
Type = "Drone"
RecordInterval = 0.033333

#[Robots.ComponentConfigs.Lidar]
#RecordInterval = 0.1
#NumRays = 32
#NumPoints = 3200
#ScannerRangeInner = 300
#ScannerRangeOuter = 5000
#ScannerAngleUp = 25
#ScannerAngleDown = 45
#bVisualizePoints = false

[Robots.ComponentConfigs.RGBDCamera]
RecordInterval = 0.033333
FOV = 90
Width = 1280
Height = 720
MaxRange = 10000.0
MinRange = 0.0
bSaveRGB = true
bSaveDepth = true

[Robots.ComponentConfigs.NormalCamera]
RecordInterval = 0.033333
FOV = 90
Width = 1280
Height = 720

[Robots.ComponentConfigs.SegmentationCamera]
RecordInterval = 0.033333
FOV = 90
Width = 1280
Height = 720

[[Robots]]
UETag = "QAQ"
Type = "Drone"
RecordInterval = 0.033333

[Robots.ComponentConfigs.RGBDCamera]
RecordInterval = 0.033333
FOV = 90
Width = 1280
Height = 720
MaxRange = 10000.0
MinRange = 0.0
bSaveRGB = true
bSaveDepth = true

[Robots.ComponentConfigs.NormalCamera]
RecordInterval = 0.033333
FOV = 90
Width = 1280
Height = 720